using System;
using System.Collections.Generic;
using UnityEngine;

public class ThemeInfo
{
	public static List<Theme> Themes = new List<Theme>();

	public ThemeInfo()
	{
		Theme theme = new Theme();
		theme.Name = "Day";
		theme.GameColors = new Color[9];
		theme.TriangleColor = new Color(0f, 0f, 0f, 0.09803922f);
		ColorUtility.TryParseHtmlString("#e76b84", out theme.GameColors[0]);
		ColorUtility.TryParseHtmlString("#5cbde4", out theme.GameColors[1]);
		ColorUtility.TryParseHtmlString("#dc6556", out theme.GameColors[2]);
		ColorUtility.TryParseHtmlString("#51d4af", out theme.GameColors[3]);
		ColorUtility.TryParseHtmlString("#ffc53c", out theme.GameColors[4]);
		ColorUtility.TryParseHtmlString("#95dd54", out theme.GameColors[5]);
		ColorUtility.TryParseHtmlString("#ee944a", out theme.GameColors[6]);
		ColorUtility.TryParseHtmlString("#7b88c1", out theme.GameColors[7]);
		ColorUtility.TryParseHtmlString("#5acb87", out theme.GameColors[8]);
		ColorUtility.TryParseHtmlString("#3F9FB5", out theme.TextBestColor);
		ColorUtility.TryParseHtmlString("#dd6a55", out theme.TextScoreColor);
		ColorUtility.TryParseHtmlString("#7c88c2", out theme.BackgroundButton);
		ColorUtility.TryParseHtmlString("#CD86F0", out theme.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#CCFF92", out theme.IconButtonColor);
		ColorUtility.TryParseHtmlString("#95dd55", out theme.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#615891", out theme.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#de6655", out theme.BackgroundRate);
		ColorUtility.TryParseHtmlString("#ffc53f", out theme.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#416bb5", out theme.BackgroundFreeCoin);
		theme.BackgroundPrefab = "Prefabs/ThemeBackground/Day";
		ThemeInfo.Themes.Add(theme);
		Theme theme2 = new Theme();
		theme2.Name = "Dark";
		theme2.GameColors = new Color[9];
		theme2.TriangleColor = new Color(0.831372559f, 0.831372559f, 0.831372559f, 0.156862751f);
		ColorUtility.TryParseHtmlString("#e76b84", out theme2.GameColors[0]);
		ColorUtility.TryParseHtmlString("#5cbde4", out theme2.GameColors[1]);
		ColorUtility.TryParseHtmlString("#dc6556", out theme2.GameColors[2]);
		ColorUtility.TryParseHtmlString("#51d4af", out theme2.GameColors[3]);
		ColorUtility.TryParseHtmlString("#ffc53c", out theme2.GameColors[4]);
		ColorUtility.TryParseHtmlString("#95dd54", out theme2.GameColors[5]);
		ColorUtility.TryParseHtmlString("#ee944a", out theme2.GameColors[6]);
		ColorUtility.TryParseHtmlString("#7b88c1", out theme2.GameColors[7]);
		ColorUtility.TryParseHtmlString("#5acb87", out theme2.GameColors[8]);
		ColorUtility.TryParseHtmlString("#FFD100", out theme2.TextBestColor);
		ColorUtility.TryParseHtmlString("#FFFFFF", out theme2.TextScoreColor);
		ColorUtility.TryParseHtmlString("#EFDFCB", out theme2.BackgroundButton);
		ColorUtility.TryParseHtmlString("#CD86F0", out theme2.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#159670", out theme2.IconButtonColor);
		ColorUtility.TryParseHtmlString("#95dd55", out theme2.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#615891", out theme2.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#de6655", out theme2.BackgroundRate);
		ColorUtility.TryParseHtmlString("#ffc53f", out theme2.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#416bb5", out theme2.BackgroundFreeCoin);
		theme2.BackgroundPrefab = "Prefabs/ThemeBackground/Dark";
		ThemeInfo.Themes.Add(theme2);
		Theme theme3 = new Theme();
		theme3.Name = "Soft";
		theme3.GameColors = new Color[9];
		theme3.TriangleColor = new Color(0f, 0f, 0f, 0.09803922f);
		ColorUtility.TryParseHtmlString("#a374b9", out theme3.GameColors[0]);
		ColorUtility.TryParseHtmlString("#cc866d", out theme3.GameColors[1]);
		ColorUtility.TryParseHtmlString("#b873aa", out theme3.GameColors[2]);
		ColorUtility.TryParseHtmlString("#687cac", out theme3.GameColors[3]);
		ColorUtility.TryParseHtmlString("#659d5e", out theme3.GameColors[4]);
		ColorUtility.TryParseHtmlString("#90b161", out theme3.GameColors[5]);
		ColorUtility.TryParseHtmlString("#c96d86", out theme3.GameColors[6]);
		ColorUtility.TryParseHtmlString("#5c99ad", out theme3.GameColors[7]);
		ColorUtility.TryParseHtmlString("#5c99ad", out theme3.GameColors[8]);
		ColorUtility.TryParseHtmlString("#c9866c", out theme3.TextBestColor);
		ColorUtility.TryParseHtmlString("#55d2b2", out theme3.TextScoreColor);
		ColorUtility.TryParseHtmlString("#5c99ac", out theme3.BackgroundButton);
		ColorUtility.TryParseHtmlString("#e16452", out theme3.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#CCFF92", out theme3.IconButtonColor);
		ColorUtility.TryParseHtmlString("#90b162", out theme3.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#c96d86", out theme3.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5c99ac", out theme3.BackgroundRate);
		ColorUtility.TryParseHtmlString("#d0846c", out theme3.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#a374ba", out theme3.BackgroundFreeCoin);
		theme3.BackgroundPrefab = "Prefabs/ThemeBackground/Soft";
		ThemeInfo.Themes.Add(theme3);
		Theme theme4 = new Theme();
		theme4.Name = "Snow";
		theme4.GameColors = new Color[9];
		theme4.TriangleColor = new Color(0f, 0f, 0f, 0.09803922f);
		ColorUtility.TryParseHtmlString("#ee6798", out theme4.GameColors[0]);
		ColorUtility.TryParseHtmlString("#FF777C", out theme4.GameColors[1]);
		ColorUtility.TryParseHtmlString("#9771d8", out theme4.GameColors[2]);
		ColorUtility.TryParseHtmlString("#6469ad", out theme4.GameColors[3]);
		ColorUtility.TryParseHtmlString("#4591cb", out theme4.GameColors[4]);
		ColorUtility.TryParseHtmlString("#FF84B5", out theme4.GameColors[5]);
		ColorUtility.TryParseHtmlString("#65BA3D", out theme4.GameColors[6]);
		ColorUtility.TryParseHtmlString("#9771d8", out theme4.GameColors[7]);
		ColorUtility.TryParseHtmlString("#ee6798", out theme4.GameColors[8]);
		ColorUtility.TryParseHtmlString("#D5FF94", out theme4.TextBestColor);
		ColorUtility.TryParseHtmlString("#FFFFFF", out theme4.TextScoreColor);
		ColorUtility.TryParseHtmlString("#5fdeb3", out theme4.BackgroundButton);
		ColorUtility.TryParseHtmlString("#FFDCF9", out theme4.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#FFFFFF", out theme4.IconButtonColor);
		ColorUtility.TryParseHtmlString("#e66e9e", out theme4.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#6ac2d6", out theme4.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5fdeb3", out theme4.BackgroundRate);
		ColorUtility.TryParseHtmlString("#8e9be9", out theme4.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#9771d8", out theme4.BackgroundFreeCoin);
		theme4.BackgroundPrefab = "Prefabs/ThemeBackground/Snow";
		ThemeInfo.Themes.Add(theme4);
		Theme theme5 = new Theme();
		theme5.Name = "Night Forest";
		theme5.GameColors = new Color[9];
		theme5.TriangleColor = new Color(0.831372559f, 0.831372559f, 0.831372559f, 0.156862751f);
		ColorUtility.TryParseHtmlString("#8e9ce7", out theme5.GameColors[0]);
		ColorUtility.TryParseHtmlString("#ef73a7", out theme5.GameColors[1]);
		ColorUtility.TryParseHtmlString("#f8c85a", out theme5.GameColors[2]);
		ColorUtility.TryParseHtmlString("#ee914b", out theme5.GameColors[3]);
		ColorUtility.TryParseHtmlString("#26a2be", out theme5.GameColors[4]);
		ColorUtility.TryParseHtmlString("#ff9fc5", out theme5.GameColors[5]);
		ColorUtility.TryParseHtmlString("#65BA3D", out theme5.GameColors[6]);
		ColorUtility.TryParseHtmlString("#9771d8", out theme5.GameColors[7]);
		ColorUtility.TryParseHtmlString("#e7776d", out theme5.GameColors[8]);
		ColorUtility.TryParseHtmlString("#D5FF94", out theme5.TextBestColor);
		ColorUtility.TryParseHtmlString("#FFDCF9", out theme5.TextScoreColor);
		ColorUtility.TryParseHtmlString("#76d696", out theme5.BackgroundButton);
		ColorUtility.TryParseHtmlString("#FD79AF", out theme5.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#454364", out theme5.IconButtonColor);
		ColorUtility.TryParseHtmlString("#e66e9e", out theme5.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#6ac2d6", out theme5.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5fdeb3", out theme5.BackgroundRate);
		ColorUtility.TryParseHtmlString("#8e9be9", out theme5.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#9771d8", out theme5.BackgroundFreeCoin);
		theme5.BackgroundPrefab = "Prefabs/ThemeBackground/NightForest";
		ThemeInfo.Themes.Add(theme5);
		Theme theme6 = new Theme();
		theme6.Name = "Autumn";
		theme6.GameColors = new Color[9];
		theme6.TriangleColor = new Color(0f, 0f, 0f, 0.09803922f);
		ColorUtility.TryParseHtmlString("#c77538", out theme6.GameColors[0]);
		ColorUtility.TryParseHtmlString("#EC6B27", out theme6.GameColors[1]);
		ColorUtility.TryParseHtmlString("#bf5624", out theme6.GameColors[2]);
		ColorUtility.TryParseHtmlString("#bf5624", out theme6.GameColors[3]);
		ColorUtility.TryParseHtmlString("#E37659", out theme6.GameColors[4]);
		ColorUtility.TryParseHtmlString("#EFA639", out theme6.GameColors[5]);
		ColorUtility.TryParseHtmlString("#c77538", out theme6.GameColors[6]);
		ColorUtility.TryParseHtmlString("#EC6B27", out theme6.GameColors[7]);
		ColorUtility.TryParseHtmlString("#E37659", out theme6.GameColors[8]);
		ColorUtility.TryParseHtmlString("#c9866c", out theme6.TextBestColor);
		ColorUtility.TryParseHtmlString("#C16B4C", out theme6.TextScoreColor);
		ColorUtility.TryParseHtmlString("#5c99ac", out theme6.BackgroundButton);
		ColorUtility.TryParseHtmlString("#e16452", out theme6.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#CCFF92", out theme6.IconButtonColor);
		ColorUtility.TryParseHtmlString("#90b162", out theme6.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#c96d86", out theme6.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5c99ac", out theme6.BackgroundRate);
		ColorUtility.TryParseHtmlString("#d0846c", out theme6.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#a374ba", out theme6.BackgroundFreeCoin);
		theme6.BackgroundPrefab = "Prefabs/ThemeBackground/Autumn";
		ThemeInfo.Themes.Add(theme6);
		Theme theme7 = new Theme();
		theme7.Name = "Galaxy";
		theme7.GameColors = new Color[9];
		theme7.TriangleColor = new Color(0.831372559f, 0.831372559f, 0.831372559f, 0.156862751f);
		ColorUtility.TryParseHtmlString("#cd84f1", out theme7.GameColors[0]);
		ColorUtility.TryParseHtmlString("#aa80ff", out theme7.GameColors[1]);
		ColorUtility.TryParseHtmlString("#6b86fe", out theme7.GameColors[2]);
		ColorUtility.TryParseHtmlString("#02ddde", out theme7.GameColors[3]);
		ColorUtility.TryParseHtmlString("#18dcff", out theme7.GameColors[4]);
		ColorUtility.TryParseHtmlString("#ff8370", out theme7.GameColors[5]);
		ColorUtility.TryParseHtmlString("#cd84f1", out theme7.GameColors[6]);
		ColorUtility.TryParseHtmlString("#6b86fe", out theme7.GameColors[7]);
		ColorUtility.TryParseHtmlString("#18dcff", out theme7.GameColors[8]);
		ColorUtility.TryParseHtmlString("#B4E53A", out theme7.TextBestColor);
		ColorUtility.TryParseHtmlString("#FFFFFF", out theme7.TextScoreColor);
		ColorUtility.TryParseHtmlString("#7BA6B9", out theme7.BackgroundButton);
		ColorUtility.TryParseHtmlString("#CD86F0", out theme7.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#5DFFF5", out theme7.IconButtonColor);
		ColorUtility.TryParseHtmlString("#CB37CB", out theme7.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#615891", out theme7.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#CB2B75", out theme7.BackgroundRate);
		ColorUtility.TryParseHtmlString("#3C9CC8", out theme7.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#416bb5", out theme7.BackgroundFreeCoin);
		theme7.BackgroundPrefab = "Prefabs/ThemeBackground/Galaxy";
		ThemeInfo.Themes.Add(theme7);
		Theme theme8 = new Theme();
		theme8.Name = "Freeze";
		theme8.GameColors = new Color[9];
		theme8.TriangleColor = new Color(0.831372559f, 0.831372559f, 0.831372559f, 0.156862751f);
		ColorUtility.TryParseHtmlString("#30c1ef", out theme8.GameColors[0]);
		ColorUtility.TryParseHtmlString("#04a297", out theme8.GameColors[1]);
		ColorUtility.TryParseHtmlString("#31d9db", out theme8.GameColors[2]);
		ColorUtility.TryParseHtmlString("#24b2b4", out theme8.GameColors[3]);
		ColorUtility.TryParseHtmlString("#0dc5b8", out theme8.GameColors[4]);
		ColorUtility.TryParseHtmlString("#20a6d0", out theme8.GameColors[5]);
		ColorUtility.TryParseHtmlString("#485eaa", out theme8.GameColors[6]);
		ColorUtility.TryParseHtmlString("#2acaca", out theme8.GameColors[7]);
		ColorUtility.TryParseHtmlString("#357abd", out theme8.GameColors[8]);
		ColorUtility.TryParseHtmlString("#31d9db", out theme8.TextBestColor);
		ColorUtility.TryParseHtmlString("#1db6c4", out theme8.TextScoreColor);
		ColorUtility.TryParseHtmlString("#3BC2ED", out theme8.BackgroundButton);
		ColorUtility.TryParseHtmlString("#7cd85b", out theme8.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#053F5F", out theme8.IconButtonColor);
		ColorUtility.TryParseHtmlString("#30c1ef", out theme8.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#04a297", out theme8.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#31d9db", out theme8.BackgroundRate);
		ColorUtility.TryParseHtmlString("#357abd", out theme8.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#416bb5", out theme8.BackgroundFreeCoin);
		theme8.BackgroundPrefab = "Prefabs/ThemeBackground/Freeze";
		theme8.Patterns.Add("snowflake1");
		theme8.Patterns.Add("snowflake2");
		theme8.Patterns.Add("snowflake3");
		ThemeInfo.Themes.Add(theme8);
		Theme theme9 = new Theme();
		theme9.Name = "Park";
		theme9.GameColors = new Color[9];
		theme9.TriangleColor = new Color(0f, 0f, 0f, 0.09803922f);
		ColorUtility.TryParseHtmlString("#ef73a6", out theme9.GameColors[0]);
		ColorUtility.TryParseHtmlString("#3b9679", out theme9.GameColors[1]);
		ColorUtility.TryParseHtmlString("#d05fbf", out theme9.GameColors[2]);
		ColorUtility.TryParseHtmlString("#5985de", out theme9.GameColors[3]);
		ColorUtility.TryParseHtmlString("#6666cc", out theme9.GameColors[4]);
		ColorUtility.TryParseHtmlString("#de6867", out theme9.GameColors[5]);
		ColorUtility.TryParseHtmlString("#d05fbf", out theme9.GameColors[6]);
		ColorUtility.TryParseHtmlString("#3b9679", out theme9.GameColors[7]);
		ColorUtility.TryParseHtmlString("#5985de", out theme9.GameColors[8]);
		ColorUtility.TryParseHtmlString("#CB6AA9", out theme9.TextBestColor);
		ColorUtility.TryParseHtmlString("#55d2b2", out theme9.TextScoreColor);
		ColorUtility.TryParseHtmlString("#5fdeb3", out theme9.BackgroundButton);
		ColorUtility.TryParseHtmlString("#B04887", out theme9.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#B04887", out theme9.IconButtonColor);
		ColorUtility.TryParseHtmlString("#FF70A3", out theme9.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#c96d86", out theme9.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5c99ac", out theme9.BackgroundRate);
		ColorUtility.TryParseHtmlString("#d0846c", out theme9.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#a374ba", out theme9.BackgroundFreeCoin);
		theme9.BackgroundPrefab = "Prefabs/ThemeBackground/Park";
		ThemeInfo.Themes.Add(theme9);
		Theme theme10 = new Theme();
		theme10.Name = "Lasvegas";
		theme10.GameColors = new Color[9];
		theme10.TriangleColor = new Color(0.831372559f, 0.831372559f, 0.831372559f, 0.156862751f);
		ColorUtility.TryParseHtmlString("#f8d239", out theme10.GameColors[0]);
		ColorUtility.TryParseHtmlString("#ffae13", out theme10.GameColors[1]);
		ColorUtility.TryParseHtmlString("#e54d4d", out theme10.GameColors[2]);
		ColorUtility.TryParseHtmlString("#ff6969", out theme10.GameColors[3]);
		ColorUtility.TryParseHtmlString("#f8d239", out theme10.GameColors[4]);
		ColorUtility.TryParseHtmlString("#ffae13", out theme10.GameColors[5]);
		ColorUtility.TryParseHtmlString("#e54d4d", out theme10.GameColors[6]);
		ColorUtility.TryParseHtmlString("#ff6969", out theme10.GameColors[7]);
		ColorUtility.TryParseHtmlString("#f8d239", out theme10.GameColors[8]);
		ColorUtility.TryParseHtmlString("#FFDF97", out theme10.TextBestColor);
		ColorUtility.TryParseHtmlString("#FFDCF9", out theme10.TextScoreColor);
		ColorUtility.TryParseHtmlString("#D46949", out theme10.BackgroundButton);
		ColorUtility.TryParseHtmlString("#FD79AF", out theme10.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#FFF4C9", out theme10.IconButtonColor);
		ColorUtility.TryParseHtmlString("#e54d4d", out theme10.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#6ac2d6", out theme10.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5fdeb3", out theme10.BackgroundRate);
		ColorUtility.TryParseHtmlString("#8e9be9", out theme10.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#9771d8", out theme10.BackgroundFreeCoin);
		theme10.BackgroundPrefab = "Prefabs/ThemeBackground/Lasvegas";
		theme10.Patterns.Add("clover");
		theme10.Patterns.Add("diamond");
		theme10.Patterns.Add("heart");
		theme10.Patterns.Add("spades");
		ThemeInfo.Themes.Add(theme10);
		Theme theme11 = new Theme();
		theme11.Name = "Cat";
		theme11.GameColors = new Color[9];
		theme11.TriangleColor = new Color(0.831372559f, 0.831372559f, 0.831372559f, 0.156862751f);
		ColorUtility.TryParseHtmlString("#9871d8", out theme11.GameColors[0]);
		ColorUtility.TryParseHtmlString("#e6a181", out theme11.GameColors[1]);
		ColorUtility.TryParseHtmlString("#f8c85a", out theme11.GameColors[2]);
		ColorUtility.TryParseHtmlString("#ef73a6", out theme11.GameColors[3]);
		ColorUtility.TryParseHtmlString("#70b9cf", out theme11.GameColors[4]);
		ColorUtility.TryParseHtmlString("#3eaf65", out theme11.GameColors[5]);
		ColorUtility.TryParseHtmlString("#9871d8", out theme11.GameColors[6]);
		ColorUtility.TryParseHtmlString("#e6a181", out theme11.GameColors[7]);
		ColorUtility.TryParseHtmlString("#f8c85a", out theme11.GameColors[8]);
		ColorUtility.TryParseHtmlString("#D5FF94", out theme11.TextBestColor);
		ColorUtility.TryParseHtmlString("#FFDCF9", out theme11.TextScoreColor);
		ColorUtility.TryParseHtmlString("#E0B9AE", out theme11.BackgroundButton);
		ColorUtility.TryParseHtmlString("#FD79AF", out theme11.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#2d2d2d", out theme11.IconButtonColor);
		ColorUtility.TryParseHtmlString("#e66e9e", out theme11.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#6ac2d6", out theme11.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5fdeb3", out theme11.BackgroundRate);
		ColorUtility.TryParseHtmlString("#8e9be9", out theme11.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#9771d8", out theme11.BackgroundFreeCoin);
		theme11.BackgroundPrefab = "Prefabs/ThemeBackground/Cat";
		theme11.Patterns.Add("meow_prints");
		ThemeInfo.Themes.Add(theme11);
		Theme theme12 = new Theme();
		theme12.Name = "Chinese";
		theme12.GameColors = new Color[9];
		theme12.TriangleColor = new Color(0.831372559f, 0.831372559f, 0.831372559f, 0.156862751f);
		ColorUtility.TryParseHtmlString("#50d0d3", out theme12.GameColors[0]);
		ColorUtility.TryParseHtmlString("#f5b82c", out theme12.GameColors[1]);
		ColorUtility.TryParseHtmlString("#4bd4ad", out theme12.GameColors[2]);
		ColorUtility.TryParseHtmlString("#d1705c", out theme12.GameColors[3]);
		ColorUtility.TryParseHtmlString("#e54b4b", out theme12.GameColors[4]);
		ColorUtility.TryParseHtmlString("#ffe336", out theme12.GameColors[5]);
		ColorUtility.TryParseHtmlString("#50d0d3", out theme12.GameColors[6]);
		ColorUtility.TryParseHtmlString("#4bd4ad", out theme12.GameColors[7]);
		ColorUtility.TryParseHtmlString("#d1705c", out theme12.GameColors[8]);
		ColorUtility.TryParseHtmlString("#FFB62F", out theme12.TextBestColor);
		ColorUtility.TryParseHtmlString("#FFDCF9", out theme12.TextScoreColor);
		ColorUtility.TryParseHtmlString("#439071", out theme12.BackgroundButton);
		ColorUtility.TryParseHtmlString("#52D3AE", out theme12.TextBestScoreColor);
		ColorUtility.TryParseHtmlString("#FFFFFF", out theme12.IconButtonColor);
		ColorUtility.TryParseHtmlString("#e54b4b", out theme12.BackgroundPlay);
		ColorUtility.TryParseHtmlString("#6ac2d6", out theme12.BackgroundMoregame);
		ColorUtility.TryParseHtmlString("#5fdeb3", out theme12.BackgroundRate);
		ColorUtility.TryParseHtmlString("#8e9be9", out theme12.BackgroundTheme);
		ColorUtility.TryParseHtmlString("#9771d8", out theme12.BackgroundFreeCoin);
		theme12.BackgroundPrefab = "Prefabs/ThemeBackground/MidAutumn";
		theme12.Patterns.Add("c1");
		theme12.Patterns.Add("c2");
		theme12.Patterns.Add("c3");
		theme12.Patterns.Add("c4");
		theme12.Patterns.Add("c5");
		theme12.Patterns.Add("c6");
		ThemeInfo.Themes.Add(theme12);
	}
}
